variables:
  SSH_AUTH_SOCK: "/tmp/ssh-jCGBqSUZJU8o/agent.25566"
  SSH_AUTH_PID: "25567"

stages:
  - build
  - test

build:
  stage: build
  script:
    - ssh-add
    - ssh -vvv git@gitlab.inria.fr
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ..
    - make -j2

test:
  stage: test
  script: ctest