starpu:
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ..
    - make -j2
    - ctest -R test_shm_s
    - cmake .. -DCHAMELEON_USE_MPI=ON -DCMAKE_INSTALL_PREFIX=$PWD/install
    - make -j2
    - ctest -R mpi_s

quark:
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake .. -DCHAMELEON_SCHED_QUARK=ON
    - make -j2
    - ctest -R test_shm_s