image: hpclib/hiepacs

stages:
  - build
  - test
  - analysis

build_starpu:
  stage: build
  artifacts:
    name: starpu_build
    expire_in: 42 minutes
    paths:
      - build
  script:
    - source .gitlab-ci-env.sh
    - git submodule update --init --recursive
    - mkdir -p build
    - cd build
    - cmake .. -DCHAMELEON_USE_MPI=ON -DCMAKE_INSTALL_PREFIX=${PWD}/install -DCMAKE_VERBOSE_MAKEFILE=ON -DMORSE_ENABLE_WARNING=ON -DMORSE_ENABLE_COVERAGE=ON
    - make -j5 | tee ../chameleon-build.log
    - make install | tee -a ../chameleon-build.log

test_starpu:
  stage: test
  dependencies:
    - build_starpu
  artifacts:
    name: starpu_test
    expire_in: 42 minutes
    paths:
      - coverage.tar.gz2
  script:
    - source .gitlab-ci-env.sh
    - git submodule update --init --recursive
    STARPU_SILENT=1 ctest --no-compress-output || /usr/bin/true
    - (cd build && STARPU_SILENT=1 ctest --no-compress-output -R test_shm_s || /usr/bin/true && ctest --no-compress-output -R mpi_s || /usr/bin/true)
    - find -name "*.gcda" | xargs tar cvjf coverage.tar.bz2

sonar:
  stage: analysis
  dependencies:
    - build_starpu
    - test_starpu
  artifacts:
    name: chameleon_analysis
    expire_in: 1 week
    paths:
      - chameleon-build.log
      - coverage/
      - chameleon-coverage.xml
      - chameleon-cppcheck.xml
      - chameleon-rats.xml
      - sonar.log
  script:
    - source .gitlab-ci-env.sh
    - tar xvjf coverage.tar.bz2
    - ./tools/analysis.sh
  only:
    - master
    - issue53/fix-ci

#starpu-simgrid:
#  stage: buildtest
#  script:
#    - source .gitlab-ci-env.sh simu
#    - git submodule update --init --recursive
#    - mkdir -p build
#    - cd build
#    - cmake .. -DCHAMELEON_SIMULATION=ON -DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MPI=OFF
#    - make -j2
#    - ctest -V
#
#quark:
#  stage: buildtest
#  script:
#    - source .gitlab-ci-env.sh
#    - git submodule update --init --recursive
#    - mkdir -p build
#    - cd build
#    - cmake .. -DCHAMELEON_SCHED_QUARK=ON
#    - make -j2
#    - ctest -V -R test_shm_s

#doc:
#  artifacts:
#    name: chameleon_doc
#    expire_in: 1 week
#    paths:
#      - build/doc/doxygen
#      - build/doc/orgmode
#  script:
#    - source .gitlab-ci-env.sh
#    - git submodule update --init --recursive
#    - mkdir -p build
#    - cd build
#    - cmake .. -DCHAMELEON_ENABLE_DOC=ON -DCHAMELEON_ENABLE_EXAMPLE=OFF -DCHAMELEON_ENABLE_TESTING=OFF -DCHAMELEON_ENABLE_TIMING=OFF
#    - make doc
