
stages:
  - build
  - test

build:
  stage: build
  script:
    - eval `ssh-agent -s`
    - ssh-add ~/.ssh/id_rsa.pub
    - ssh -vvv git@gitlab.inria.fr
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ..
    - make -j2

test:
  stage: test
  script: ctest