starpu:
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ..
    - make -j2
    - ctest -R test_shm_s
    - cmake .. -DCHAMELEON_USE_MPI=ON -DCMAKE_INSTALL_PREFIX=$PWD/install
    - make -j2
    - ctest -V -R mpi_s

starpu-simgrid:
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - . $HOME/spack/share/spack/setup-env.sh
    - spack load hwloc && spack load fxt && spack load simgrid && spack load starpu
    - cmake .. -DCHAMELEON_SIMULATION=ON -DCHAMELEON_USE_CUDA=ON -DCHAMELEON_USE_MAGMA=OFF -DCHAMELEON_USE_MPI=OFF
    - make -j2
    - ctest -V

quark:
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake .. -DCHAMELEON_SCHED_QUARK=ON
    - make -j2
    - ctest -V -R test_shm_s